function pred = run_fixed_fivefold(X, y, foldId, nFolds, spec, seedBase)
% Generate deterministic out-of-fold FCNN predictions for one specification.
pred = nan(size(y));
for iFold = 1:nFolds
    trainMask = foldId ~= iFold;
    valMask = foldId == iFold;
    trainD99 = prctile(y(trainMask), 99);
    weights = grsl.depth.make_depth_weights(y(trainMask), trainD99, ...
        spec.DepthWeightRho, spec.DepthWeightPower);
    rng(seedBase + iFold, 'twister');
    mdl = grsl.model.train_fcnn(X(trainMask,:), y(trainMask), ...
        'LayerSizes', spec.LayerSizes, ...
        'Activations', spec.Activation, ...
        'Standardize', true, ...
        'Lambda', spec.Lambda, ...
        'IterationLimit', spec.IterationLimit, ...
        'Weights', weights);
    pred(valMask) = grsl.model.predict_fcnn(mdl, X(valMask,:));
end
assert(all(isfinite(pred)), 'Missing five-fold predictions.');
end
