function plot_depth_binned_rmse_bias(ax, T, site, hMax, dTrain99, plotMax, panelTitle)
% Draw current self/independent RMSE and Bias curves for one site.
siteRows = T(T.Site == site, :);
self = siteRows(siteRows.Validation == "Self-Validation", :);
independent = siteRows(siteRows.Validation == "Independent Validation", :);
selfGood = self.Reliable;
independentGood = independent.Reliable;

hold(ax, 'on');
box(ax, 'on');
grid(ax, 'on');
hSelfRMSE = plot(ax, self.DepthCenter_m(selfGood), self.RMSE_m(selfGood), ...
    '-o', 'Color', [0.00 0.55 0.55], 'MarkerFaceColor', [0.00 0.55 0.55], ...
    'LineWidth', 1.7, 'MarkerSize', 5);
hSelfBias = plot(ax, self.DepthCenter_m(selfGood), self.Bias_m(selfGood), ...
    '--s', 'Color', [0.47 0.67 0.19], 'MarkerFaceColor', [0.47 0.67 0.19], ...
    'LineWidth', 1.7, 'MarkerSize', 5);
hIndependentRMSE = plot(ax, independent.DepthCenter_m(independentGood), ...
    independent.RMSE_m(independentGood), '-^', 'Color', [0.93 0.48 0.10], ...
    'MarkerFaceColor', [0.93 0.48 0.10], 'LineWidth', 1.7, 'MarkerSize', 5);
hIndependentBias = plot(ax, independent.DepthCenter_m(independentGood), ...
    independent.Bias_m(independentGood), '--d', 'Color', [0.49 0.18 0.56], ...
    'MarkerFaceColor', [0.49 0.18 0.56], 'LineWidth', 1.7, 'MarkerSize', 5);
yline(ax, 0, ':', 'Color', [0.35 0.35 0.35], ...
    'LineWidth', 1.0, 'HandleVisibility', 'off');
hHmax = xline(ax, hMax, '-', 'Color', [0.00 0.45 0.85], 'LineWidth', 2.0);
hDtrain = xline(ax, dTrain99, '-', 'Color', [0.90 0.05 0.05], 'LineWidth', 2.0);

xlim(ax, [0 plotMax]);
xticks(ax, 0:5:plotMax);
xlabel(ax, 'Reference Depth (m)', 'FontName', 'Times New Roman', ...
    'FontSize', 12, 'FontWeight', 'bold');
ylabel(ax, 'Error (m)', 'FontName', 'Times New Roman', ...
    'FontSize', 12, 'FontWeight', 'bold');
title(ax, panelTitle, 'FontName', 'Times New Roman', ...
    'FontSize', 14, 'FontWeight', 'bold');
legend(ax, [hSelfRMSE hSelfBias hIndependentRMSE hIndependentBias ...
    hHmax hDtrain], ...
    {'Self-validation RMSE', 'Self-validation Bias', ...
    'Independent-validation RMSE', 'Independent-validation Bias', ...
    sprintf('H_{max} = %.2f m', hMax), ...
    sprintf('D_{train,99} = %.2f m', dTrain99)}, ...
    'Location', 'northwest', 'NumColumns', 2, ...
    'FontName', 'Times New Roman', 'FontSize', 9, ...
    'Interpreter', 'tex', 'Box', 'on');
set(ax, 'FontName', 'Times New Roman', 'FontSize', 11, ...
    'LineWidth', 1, 'TickDir', 'out', 'Layer', 'top');
hold(ax, 'off');
end
