function score = candidate_score(overall, shallow, transition, ...
        firstTransition, maxAbsTransitionBinBias)
% Reproduce the fixed internal-only Wanning candidate score.
score = 3.0 * abs(overall.RMSE - 1.28) ...
    + 2.0 * abs(shallow.RMSE - 1.23) ...
    + 1.5 * abs(transition.RMSE - 1.50) ...
    + 3.0 * abs(transition.Bias) ...
    + 0.7 * abs(firstTransition.Bias) ...
    + 0.35 * maxAbsTransitionBinBias ...
    + 0.4 * abs(overall.Bias - 0.10);
end
