function spec = make_spec(id, featureMode, layers, activation, ...
        lambda, iterations, rho, power)
% Build one immutable Wanning FCNN candidate specification.
spec = struct('ID', id, 'FeatureMode', featureMode, ...
    'LayerSizes', layers, 'Activation', activation, 'Lambda', lambda, ...
    'IterationLimit', iterations, 'DepthWeightRho', rho, ...
    'DepthWeightPower', power);
end
