function plot_site_row(layout, input, bins)
% Draw direct-pair and residual panels for one site.
T = input.Pairs;
m = input.Metrics;
axisLimit = [0 30];
ax1 = nexttile(layout);
hold(ax1, 'on'); box(ax1, 'on'); grid(ax1, 'on');
hPoints = scatter(ax1, T.reference_depth, T.is2_depth, 14, ...
    [0.18 0.48 0.78], 'filled', 'MarkerFaceAlpha', 0.45, ...
    'MarkerEdgeAlpha', 0.25);
hOne = plot(ax1, axisLimit, axisLimit, '--', ...
    'Color', [0.25 0.25 0.25], 'LineWidth', 1.3);
uistack(hOne, 'top'); uistack(hPoints, 'bottom');
xlim(ax1, axisLimit); ylim(ax1, axisLimit); axis(ax1, 'square');
xlabel(ax1, 'Independent Reference Depth (m)');
ylabel(ax1, 'ICESat-2 Depth (m)');
title(ax1, sprintf('%s: direct pairs', input.Name));
annotationText = sprintf(['N = %d; tracks = %d\nBias = %+.3f m\n' ...
    'RMSE = %.3f m; MAE = %.3f m\nR^2 = %.3f'], height(T), ...
    numel(unique(T.track)), m.Bias_m, m.RMSE_m, m.MAE_m, m.OLS_R2);
text(ax1, 0.04, 0.96, annotationText, 'Units', 'normalized', ...
    'VerticalAlignment', 'top', 'FontName', 'Times New Roman', ...
    'FontSize', 9, 'BackgroundColor', 'white', ...
    'EdgeColor', [0.5 0.5 0.5], 'Margin', 4);
legend(ax1, [hPoints hOne], {'Matched pairs','1:1 line'}, ...
    'Location', 'southeast', 'FontSize', 8, 'Box', 'on');

ax2 = nexttile(layout);
hold(ax2, 'on'); box(ax2, 'on'); grid(ax2, 'on');
hPairs = scatter(ax2, T.reference_depth, T.residual, 13, ...
    [0.35 0.35 0.35], 'filled', 'MarkerFaceAlpha', 0.28, ...
    'MarkerEdgeAlpha', 0.15);
hZero = yline(ax2, 0, '--', 'Color', [0.15 0.15 0.15], 'LineWidth', 1.1);
hMean = yline(ax2, m.Bias_m, ':', 'Color', [0.10 0.40 0.78], 'LineWidth', 1.4);
good = bins.Reliable & isfinite(bins.Bias_m);
hBin = plot(ax2, bins.DepthCenter_m(good), bins.Bias_m(good), '-o', ...
    'Color', [0.85 0.15 0.15], 'MarkerFaceColor', [0.85 0.15 0.15], ...
    'LineWidth', 1.6, 'MarkerSize', 4.5);
uistack(hPairs, 'bottom'); uistack([hZero hMean hBin], 'top');
xlim(ax2, axisLimit);
resSpan = max([abs(T.residual); abs(bins.Bias_m(good)); abs(m.Bias_m); 0.5], ...
    [], 'omitnan');
ylim(ax2, [-1.12 * resSpan 1.12 * resSpan]);
xlabel(ax2, 'Independent Reference Depth (m)');
ylabel(ax2, 'ICESat-2 - Reference (m)');
title(ax2, sprintf('%s: residuals', input.Name));
legend(ax2, [hPairs hZero hMean hBin], ...
    {'Matched pairs','Zero residual','Overall Bias','2 m-bin Bias'}, ...
    'Location', 'southwest', 'FontSize', 8, 'Box', 'on');
set([ax1 ax2], 'FontName', 'Times New Roman', 'FontSize', 10, ...
    'LineWidth', 0.9, 'Layer', 'top');
end
