function add_panel_label(fig, position, label, fontName, darkText, fontSize)
% Add a consistently positioned figure-level panel label.
if darkText, color = 'k'; else, color = 'w'; end
labelWidth = 0.070;
labelHeight = 0.065;
labelPosition = [position(1) + position(3) - labelWidth - 0.018, ...
    position(2) + position(4) - labelHeight - 0.004, labelWidth, labelHeight];
annotation(fig, 'textbox', labelPosition, 'String', label, ...
    'LineStyle', 'none', 'FitBoxToText', 'off', ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', ...
    'FontName', fontName, 'FontSize', fontSize, 'FontWeight', 'bold', ...
    'Color', color, 'Margin', 0);
end
